version: "3.8"

services:
  notes_db:
    image: postgres:15
    container_name: notes_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: notes_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - notes-network


networks:
  notes-network:
    name: notes-network
    external: true


volumes:
  postgres_data:
