version: "3.8"

services:
  notes_api:
    build: .
    container_name: notes_api
    restart: unless-stopped
    ports:
      - "8050:8050"
    env_file:
      - .env
    networks:
      - notes-network


networks:
  notes-network:
    name: notes-network
    external: true


volumes:
  postgres_data:
